// Global System Engine Toggles
let shadersActive = false;
let chaosActive = false;
let pigBuffActive = false;

// SYSTEM INITIALIZATION COMMAND
// Type "activate_all" in chat to turn on all graphics and mob behaviors at once
player.onChat("activate_all", function () {
    shadersActive = true;
        chaosActive = true;
            pigBuffActive = true;
                
                    // Stabilize world simulation rules
                        player.execute("gamerule doWeatherCycle false");
                            player.execute("time set day");
                                
                                    player.say("System: Master Code Activated. Visual shaders, entity chaos, and muscle mutation modules online.");
                                    });
                                    
                                    // SYSTEM TERMINATION COMMAND
                                    // Type "deactivate_all" in chat to restore standard vanilla rules and behaviors
                                    player.onChat("deactivate_all", function () {
                                        shadersActive = false;
                                            chaosActive = false;
                                                pigBuffActive = false;
                                                    
                                                        player.execute("gamerule doWeatherCycle true");
                                                            player.say("System: Master Code Deactivated. Restoring standard world configuration rules.");
                                                            });
                                                            
                                                            // ========================================================
                                                            // SECTION 1: PURE GRAPHICS & VISUAL ENGINE LOOPS
                                                            // ========================================================
                                                            
                                                            // 1. DYNAMIC WATER WAVE ANIMATION
                                                            let waveToggle = true;
                                                            loops.forever(function () {
                                                                if (shadersActive) {
                                                                        let pPos = player.position();
                                                                                let pX = Math.floor(pPos.getValue(Axis.X));
                                                                                        let pY = Math.floor(pPos.getValue(Axis.Y));
                                                                                                let pZ = Math.floor(pPos.getValue(Axis.Z));
                                                                                                
                                                                                                        for (let xOffset = -5; xOffset <= 5; xOffset += 2) {
                                                                                                                    for (let zOffset = -5; zOffset <= 5; zOffset += 2) {
                                                                                                                                    for (let yOffset = 2; yOffset >= -4; yOffset--) {
                                                                                                                                                        let checkTarget = positions.create(pX + xOffset, pY + yOffset, pZ + zOffset);
                                                                                                                                                                            
                                                                                                                                                                                                if (blocks.testForBlock(WATER, checkTarget)) {
                                                                                                                                                                                                                        if (waveToggle) {
                                                                                                                                                                                                                                                    player.execute(`setblock ${pX + xOffset} ${pY + yOffset + 1} ${pZ + zOffset} water`);
                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                        player.execute(`setblock ${pX + xOffset} ${pY + yOffset + 1} ${pZ + zOffset} air`);
                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                        break; 
                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                        waveToggle = !waveToggle;
                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                loops.pause(1400); 
                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                // 2. UNDERWATER SUNRAY & CAUSTIC ENGINE
                                                                                                                                                                                                                                                                                                                                                                                                                                loops.forever(function () {
                                                                                                                                                                                                                                                                                                                                                                                                                                    if (shadersActive) {
                                                                                                                                                                                                                                                                                                                                                                                                                                            let pPos = player.position();
                                                                                                                                                                                                                                                                                                                                                                                                                                                    let pX = Math.floor(pPos.getValue(Axis.X));
                                                                                                                                                                                                                                                                                                                                                                                                                                                            let pY = Math.floor(pPos.getValue(Axis.Y));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    let pZ = Math.floor(pPos.getValue(Axis.Z));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for (let rayCount = 0; rayCount < 4; rayCount++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        let rx = pX + Math.randomRange(-8, 8);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    let rz = pZ + Math.randomRange(-8, 8);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for (let ry = pY; ry >= pY - 12; ry--) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            let groundCheck = positions.create(rx, ry, rz);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            let blockAbove = positions.create(rx, ry + 1, rz);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (!blocks.testForBlock(AIR, groundCheck) && !blocks.testForBlock(WATER, groundCheck) && blocks.testForBlock(WATER, blockAbove)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for (let depthHeight = 1; depthHeight <= 7; depthHeight++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        player.execute(`particle minecraft:endrod ${rx} ${ry + depthHeight} ${rz} 0.1 0.6 0.1 0.005 1`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            loops.pause(1000); 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // 3. VIBRANT PLAYER GLOW AURA
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            let colorPhase = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            loops.forever(function () {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (shadersActive) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        let playerPos = player.position();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                let px = playerPos.getValue(Axis.X);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        let py = playerPos.getValue(Axis.Y);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                let pz = playerPos.getValue(Axis.Z);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (colorPhase === 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    player.execute(`particle minecraft:electric_spark_particle ${px} ${py + 1} ${pz} 0.4 0.6 0.4 0.05 4`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                colorPhase = 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } else if (colorPhase === 1) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    player.execute(`particle minecraft:redstone_laser_particle ${px} ${py + 0.5} ${pz} 0.3 0.5 0.3 0.08 5`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                colorPhase = 2;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    player.execute(`particle minecraft:shulk_bullet ${px} ${py + 1.2} ${pz} 0.5 0.5 0.5 0.02 2`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                colorPhase = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                loops.pause(1800); 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // ========================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // SECTION 2: WEIRD MOB PHYSICS & CHAOS LOOPS
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // ========================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // 1. FLOATING VILLAGER CORRUPTION
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                loops.forever(function () {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (chaosActive) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            player.execute("effect @e[type=villager,r=15] levitation 2 5 true");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    player.execute("execute @e[type=villager,r=15] ~ ~ ~ particle minecraft:villager_happy ~ ~1 ~");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            loops.pause(500); 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // 2. ROCKET CHICKEN GLITCH
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            player.onTravelled(TravelMethod.Walk, function () {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (chaosActive) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        player.execute("execute @e[type=chicken,r=20] ~ ~ ~ particle minecraft:knockback_roar_particle ~ ~ ~ 0.1 0.1 0.1 0.5 1");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                player.execute("effect @e[type=chicken,r=20] speed 1 20 true");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // 3. STRONG/BUFF PIG MUTATION
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    loops.forever(function () {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (pigBuffActive) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                player.execute("playanimation @e[type=pig,name=giant] animation.ghast.scale r 99");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        player.execute("effect @e[type=pig,name=giant] resistance 5 5 true");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                player.execute("effect @e[type=pig,name=giant] strength 5 5 true");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        loops.pause(1000); 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        player.onChat("run", function () {
	
})
